### ISSUE TITLE
Indicator value can not be calculated because of the the error " Bad date or time value: Time end cannot be set in live mode"

### ISSUE THREAD

**Issue by mydanniel** [hal9000cc/live_trading_indicators#5]
Hi i have run the following code:
import live_trading_indicators as lti
import datetime as dt
import talib as ta
import pandas as pd

print(f'Now is {utcnow} UTC')
indicators = lti.Indicators('binance',20230701,with_incomplete_bar=True)
print(indicators.time_end)
ohlcv = indicators.OHLCV('btcusdt', '1h')
sma = indicators.SMA('btcusdt', '1h',period = 10)
print(indicators.time_end)

It give me an error, when executing the  code to calculate SMA, could you please take a look at it?
Traceback (most recent call last):
  File "ltiimcompletebar.py", line 13, in <module>
    sma = indicators.SMA('btcusdt', '1h',period = 10)
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 445, in __call__
    return self.indicators.get_indicator_out(self.indicator_name, self.indicator_module, symbols, use_timeframe,
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 298, in get_indicator_out
    out = self.get_indicator_out_cached(indicator_name, indicator_module, symbols, timeframe, indicator_kwargs,
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 278, in get_indicator_out_cached
    out_valid = indicator_module.get_indicator_out(self, symbols, timeframe, out_for_grow, **indicator_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/SMA.py", line 9, in get_indicator_out
    ohlcv = indicators.OHLCV.full_data(symbol, timeframe)
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 432, in full_data
    return self.indicators.get_indicator_out(self.indicator_name, self.indicator_module, symbols, timeframe,
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 290, in get_indicator_out
    use_time_begin, use_time_end = self.check_call_time_intervals(time_begin, time_end, timeframe)
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 223, in check_call_time_intervals
    return self.check_call_time_intervals_live(time_begin, time_end, timeframe)
  File "/usr/local/lib/python3.8/dist-packages/live_trading_indicators/indicators_set/__init__.py", line 205, in check_call_time_intervals_live
    raise LTIExceptionBadTimeParameter('Time end cannot be set in live mode')
live_trading_indicators.exceptions.LTIExceptionBadTimeParameter: Bad date or time value: Time end cannot be set in live mode

**Comment by hal9000cc** [comment]
Fixed it in the master. There will be a release later.

**Comment by Etyoin** [comment]
Hi,

Could you please help I have the same issue as "mydanniel" above? How can I fix this error?

My Python version 3.10

Thanks your reply in advance. 

This is my test code to test indicators live data.

import datetime as dt
import pandas as pd
import live_trading_indicators as lti

lti.config(max_empty_bars_fraction=-1, max_empty_bars_consecutive=-1)

utcnow = dt.datetime.utcnow()
print(f'Now is {utcnow} UTC')
indicators = lti.Indicators('ccxt.bybit', utcnow - dt.timedelta(minutes=3), with_incomplete_bar=True, exchange_params={'limit': 200})
ohlcv = indicators.OHLCV('ETHUSDT', '1m')
obv = indicators.OBV('ETHUSDT', '1m')
macd = indicators.MACD('ETHUSDT, '1m', period_short=15, period_long=26, period_signal=9)
print(ohlcv.pandas())


Now is 2025-03-30 11:19:50.640623 UTC
2025-03-30 12:19:56:root:11792:102 INFO Download using xxct.bybit symbol ETHUSDT timeframe 1m from 2025-03-30T00:00:00.000, bars: 200
2025-03-30 12:19:56:root:11792:102 INFO Download using xxct.bybit symbol ETHUSDT timeframe 1m from 2025-03-30T03:20:00.000, bars: 200
2025-03-30 12:19:57:root:11792:102 INFO Download using xxct.bybit symbol ETHUSDT timeframe 1m from 2025-03-30T06:40:00.000, bars: 200
2025-03-30 12:19:57:root:11792:102 INFO Download using xxct.bybit symbol ETHUSDT timeframe 1m from 2025-03-30T10:00:00.000, bars: 80
Traceback (most recent call last):
  File "e:\Docs\Trade\Python\lti_test.py", line 11, in <module>
    obv = indicators.OBV('ETHUSDT', '1m')
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 445, in __call__
    return self.indicators.get_indicator_out(self.indicator_name, self.indicator_module, symbols, use_timeframe,
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 295, in get_indicator_out
    out = indicator_module.get_indicator_out(self, symbols, timeframe, use_time_begin, use_time_end,
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\OBV.py", line 13, in get_indicator_out
    ohlcv = indicators.OHLCV(symbol, timeframe, time_begin, time_end)
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 445, in __call__
    return self.indicators.get_indicator_out(self.indicator_name, self.indicator_module, symbols, use_timeframe,
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 290, in get_indicator_out
    use_time_begin, use_time_end = self.check_call_time_intervals(time_begin, time_end, timeframe)
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 223, in check_call_time_intervals
    return self.check_call_time_intervals_live(time_begin, time_end, timeframe)
  File "e:\Docs\Trade\Python\myenv\lib\site-packages\live_trading_indicators\indicators_set\__init__.py", line 205, in check_call_time_intervals_live
    raise LTIExceptionBadTimeParameter('Time end cannot be set in live mode')
live_trading_indicators.exceptions.LTIExceptionBadTimeParameter: Bad date or time value: Time end cannot be set in live mode

**Comment by hal9000cc** [comment]
Fix in 1.0.1
